---
apiVersion: v1
kind: Secret
metadata:
  name: {{.POSTGREST_NAME}}
type: Opaque
data:
  dbUri: "postgres://{{.DB_REF_REFERENCE_AUTHENTICATOR_USERNAME}}:{{.DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD}}@{{.DB_REF_HOSTNAME}}:5432/{{.DB_REF_REFERENCE_DBNAME}}{{.DB_REF_OPTIONS | b64enc }}"
  jwtSecret: "{{.KEYCLOAK_JWT}}"
